import os
CAR_ID = "2"
GLB_DIRECTORY = os.path.join(os.path.dirname(os.path.abspath(__file__)), "glb")
FPS = 30
DURATION_SECONDS = 60
TOTAL_FRAMES = FPS * DURATION_SECONDS
START_Y = 40.0
END_Y = -40.0
CAMERA_X_OFFSET = 5.0
CAMERA_HEIGHT = 1.7

# 解像度設定 (4K)
RESOLUTION_X = 3840
RESOLUTION_Y = 2160
RESOLUTION_PERCENTAGE = 100
